LOCK_CHAT_RESTRICTION = {
    "all": {
        "can_send_messages": False,
        "can_send_polls": False,
        "can_send_other_messages": False,
        "can_add_web_page_previews": False,
        "can_change_info": False,
        "can_invite_users": False,
        "can_pin_messages": False,
        "can_manage_topics": False,
        "can_send_audios": False,
        "can_send_documents": False,
        "can_send_photos": False,
        "can_send_videos": False,
        "can_send_video_notes": False,
        "can_send_voice_notes": False,
    },
    # Add necessary permissions for each lock type.
}

UNLOCK_CHAT_RESTRICTION = {
    "all": {
        "can_send_messages": True,
        "can_send_polls": True,
        "can_send_other_messages": True,
        "can_add_web_page_previews": True,
        "can_change_info": True,
        "can_invite_users": True,
        "can_pin_messages": True,
        "can_manage_topics": True,
        "can_send_audios": True,
        "can_send_documents": True,
        "can_send_photos": True,
        "can_send_videos": True,
        "can_send_video_notes": True,
        "can_send_voice_notes": True,
    },
    # Add necessary permissions for each unlock type.
}

LOCKABLES = {
    "all": "Restricts everything.",
    "album": "Deletes photos or videos sent as an album.",
    "anonchannel": "Messages sent through anonymous channels.",
    "audio": "Restricts audio media messages.",
    "bot": "Restricts adding bots to the group.",
    "botlink": "Messages containing bot links or usernames ending with 'bot'.",
    "btn": "Messages containing inline buttons.",
    "cjk": "Messages containing Chinese, Japanese, or Korean characters.",
    "command": "Messages starting with '/'.",
    "contact": "Restricts contact media messages.",
    "cyrillic": "Messages containing Cyrillic characters (e.g., Russian, Ukrainian).",
    "document": "Restricts document media messages.",
    "email": "Messages containing emails.",
    "emoji": "Messages containing any emoji.",
    "emoji_custom": "Messages containing custom Telegram emojis.",
    "dice": "Messages with dice animations.",
    "external_reply": "Replies to messages from other chats.",
    "forward": "Restricts forwarded messages.",
    "game": "Restricts game messages.",
    "gif": "Restricts GIFs.",
    "inline": "Restricts inline bot results.",
    "invitelink": "Messages containing invite links to Telegram groups or channels.",
    "location": "Restricts location media messages.",
    "phone": "Messages containing phone numbers.",
    "photo": "Restricts photo messages.",
    "poll": "Restricts poll messages.",
    "rtl": "Messages with right-to-left characters (e.g., Arabic, Hebrew).",
    "spoiler": "Messages containing spoilers.",
    "sticker": "Restricts stickers.",
    "animated_sticker": "Restricts animated stickers.",
    "premium_sticker": "Restricts premium stickers.",
    "text": "Restricts text messages.",
    "url": "Messages containing URLs.",
    "video": "Restricts video messages.",
    "videonote": "Restricts video notes.",
    "voice": "Restricts voice messages.",
}